#!/bin/bash


# Project name
#$ -P cbs


#Running the main simulation
#Arguments M, p, nstart, initial_iter, N
qsub simsub_12states.qsub 100 .95 5 2000 12
qsub simsub_12states.qsub 250 .95 5 2000 12
qsub simsub_12states.qsub 500 .95 5 2000 12
qsub simsub_12states.qsub 100 .85 5 2000 12
qsub simsub_12states.qsub 250 .85 5 2000 12
qsub simsub_12states.qsub 500 .85 5 2000 12
qsub simsub_12states.qsub 100 .75 5 2000 12
qsub simsub_12states.qsub 250 .75 5 2000 12
qsub simsub_12states.qsub 500 .75 5 2000 12
